Repository Sfacspace-GuardNine/Sfacspace-FE, pull requests merged in 2024-08, with the labels that each got.

#2 [#1] Chore: 프로젝트 세팅
  .eslintrc.json
  .github/ISSUE_TEMPLATE/issue_tmplate.md
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.js
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  commitlint.config.cjs
  next.config.mjs
  package.json
  postcss.config.mjs
  public/icons/.empty
  public/images/.empty
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/.empty
  src/components/Button.tsx
  src/stories/Button.stories.ts
  src/type/.empty
  src/utils/cn.ts
  tailwind.config.ts
  tsconfig.json
Labels: ⚙️ Chore

#7 [#3] style: tailwind 색상 토큰값 변경
  src/app/globals.css
Labels: 🎨 Style

#9 [#8] chore: 스토리북 배포 workflow 작성
  .github/workflows/next-build.yaml
  .github/workflows/storybook.yaml
  .gitignore
  .storybook/main.ts
  package-lock.json
  package.json
Labels: ⚙️ Chore

#10 [#5] feat: 공통 컴포넌트 작업
  .idea/.gitignore
  .idea/Sfacspace-FE.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/git_toolbox_blame.xml
  .idea/git_toolbox_prj.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/material_theme_project_new.xml
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
  package.json
  public/images/arrow_left.svg
  public/images/file_empty.svg
  public/images/flawdetector-logo.svg
  public/images/footer-pattern.svg
  public/images/info_error.svg
  public/images/info_success.svg
  public/images/info_warning.svg
  public/images/service-card/service_card_blue.png
  public/images/service-card/service_card_green.png
  public/images/service-card/service_card_pink.png
  public/images/service-card/service_card_purple.png
  public/images/service-card/service_card_red.png
  public/images/service-card/service_card_yellow.png
  public/images/sfacspace-logo.svg
  src/components/Button.tsx
  src/components/CheckedFileItem.tsx
  src/components/CheckedFiles.tsx
  src/components/Footer.tsx
  src/components/Gnb.tsx
  src/components/GnbTitle.tsx
  src/components/InfoBox.tsx
  src/components/Label.tsx
  src/components/ProgressBar.tsx
  src/components/Ranking.tsx
  src/components/RankingItem.tsx
  src/components/ServiceCard.tsx
  src/components/TitleDefault.tsx
  src/components/ToolTip.tsx
  src/stories/Button.stories.ts
  src/stories/CheckedFiles.stories.ts
  src/stories/Footer.stories.ts
  src/stories/Gnb.stories.ts
  src/stories/GnbTitle.stories.ts
  src/stories/InfoBox.stories.ts
  src/stories/Label.stories.ts
  src/stories/ProgressBar.stories.ts
  src/stories/Ranking.stories.ts
  src/stories/ServiceCard.stories.ts
  src/stories/TitleDefault.stories.ts
  src/stories/ToolTip.stories.ts
Labels: ✨Feature

#15 [#13] Feat: Chips컴포넌트 구현
  public/images/X.svg
  public/images/caret-down-disabled.svg
  public/images/caret-down.svg
  public/images/document_icon.svg
  src/components/AssistChip.tsx
  src/components/FilterChip.tsx
  src/components/InputChip.tsx
  src/components/SuggestionChip.tsx
  src/stories/AssistChip.stories.ts
  src/stories/FilterChip.stories.ts
  src/stories/InputChip.stories.ts
  src/stories/SuggestionChip.stories.ts
Labels: ✨Feature

#12 [#11] Feat: Button 컴포넌트 구현
  src/app/globals.css
  src/components/Button.tsx
  src/stories/Button.stories.ts
  tailwind.config.ts
Labels: ✨Feature

#28 [#18] Feat: List컴포넌트 구현
  public/images/alert-triangle.svg
  public/images/check.svg
  public/images/checkCircle.svg
  public/images/folder-open.svg
  public/images/list-caption.svg
  public/images/loader.svg
  public/images/profile-default.png
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/stories/List.stories.ts
Labels: ✨Feature

#29 [#26] feat: Switch 컴포넌트 작업
  public/images/switch-check.svg
  public/images/switch-x.svg
  src/components/Switch.tsx
  src/stories/Switch.stories.ts
Labels: ✨Feature

#24 [#22]feat: Pagination component 구현
  package-lock.json
  public/images/arrow_right.svg
  src/components/PageButton.tsx
  src/components/Pagination.tsx
  src/stories/Pagination.stories.ts
Labels: ✨Feature

#20 [#19]feat: Input component 구현
  src/components/Input.tsx
  src/stories/Input.stories.ts
Labels: ✨Feature

#33 [#32] Feat: Floating컴포넌트 구현
  public/images/floating-arrow.svg
  public/images/floating-ask-enabled.svg
  public/images/floating-ask-hovered.svg
  public/images/hover-floating-arrow.svg
  src/components/Floating.tsx
  src/stories/Floating.stories.ts
Labels: ✨Feature

#31 [#27] Feat: Popup컴포넌트 구현
  public/images/logo_bug.svg
  src/components/Popup/Popup.tsx
  src/hooks/usePopup.ts
  src/stories/Popup.stories.tsx
Labels: ✨Feature

#37 [#36] Feat: SecureAnalyzer컴포넌트 구현
  public/images/analyzing-icon.svg
  public/images/completed-icon.svg
  public/images/folder-dashed.svg
  public/images/glass-plus.svg
  public/images/logo-bug2.svg
  src/components/SecureAnalyzer.tsx
  src/stories/SecureAnalyzer.stories.ts
Labels: ✨Feature

#35 [#25] Feat: Dropdown 컴포넌트 구현
  public/images/arrow_down.svg
  public/images/checked.svg
  src/components/Dropdown.tsx
  src/components/DropdownButton.tsx
  src/components/DropdownItem.tsx
  src/components/DropdownList.tsx
  src/stories/Dropdown.stories.ts
Labels: ✨Feature

#40 [#39] Feat: 취약점DB 페이지 구현
  src/app/vulndb/[postId]/page.tsx
  src/app/vulndb/layout.tsx
  src/app/vulndb/page.tsx
  src/components/AssistChip.tsx
  src/components/CardHovered.tsx
  src/components/Floating.tsx
  src/components/OnlyCard.tsx
  src/components/Pagination.tsx
  src/components/SmallCard.tsx
  src/components/SuggestionChip.tsx
  src/components/VulnDB/VulnerabilityTable.tsx
  src/stories/VulnerabilityTable.stories.ts
Labels: ✨Feature

#42 [#34] feat: MY저장소 퍼블리싱
  next.config.mjs
  package-lock.json
  package.json
  public/icons/arrow-left.svg
  public/icons/arrow-right.svg
  public/icons/plus-icon.svg
  public/images/mylibrary-pattern.svg
  src/app/layout.tsx
  src/app/my/(not_library)/layout.tsx
  src/app/my/(not_library)/profile/page.tsx
  src/app/my/(not_library)/setting/page.tsx
  src/app/my/help/layout.tsx
  src/app/my/help/page.tsx
  src/app/my/library/(container)/clipping/page.tsx
  src/app/my/library/(container)/detected/page.tsx
  src/app/my/library/(container)/layout.tsx
  src/app/my/library/groups/[folderId]/page.tsx
  src/app/my/library/groups/layout.tsx
  src/app/my/library/layout.tsx
  src/app/my/library/page.tsx
  src/app/my/page.tsx
  src/components/ClippingCard.tsx
  src/components/Dropdown.tsx
  src/components/DropdownButton.tsx
  src/components/DropdownItem.tsx
  src/components/DropdownList.tsx
  src/components/FileCard.tsx
  src/components/Footer.tsx
  src/components/Gnb.tsx
  src/components/GnbTitle.tsx
  src/components/InfoBox.tsx
  src/components/InfoBoxDetail.tsx
  src/components/Input.tsx
  src/components/InputChip.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/SecureAnalyzer.tsx
  src/components/Switch.tsx
  src/components/ThreeDotDropDown.tsx
  src/components/TitleDefault.tsx
  src/components/my/ClippingFiles.tsx
  src/components/my/DetectedFiles.tsx
  src/components/my/FileAnalyze.tsx
  src/components/my/LibraryFiles.tsx
  src/components/my/MyLibraryBackButton.tsx
  src/components/my/ResultAnalyze.tsx
  src/components/my/SortFiles.tsx
  src/stories/ClippingCard.stories.ts
  src/stories/Dropdown.stories.ts
  src/stories/FileCard.stories.ts
  src/styles/swiper-navigation.css
Labels: ✨Feature

#44 [#43] Feat: login페이지 구현
  public/images/loginUi-pattern.svg
  src/app/login/page.tsx
Labels: ✨Feature

#48 [#46] chore: firebase 설치
  package-lock.json
  package.json
  src/firebase.ts
Labels: ✨Feature
